x-service: &service
  image: blockcast/cdn_gateway_go:${IMAGE_VERSION:-stable}
  restart: unless-stopped
  network_mode: "service:blockcastd"
  volumes:
    - ${HOME}/.blockcast/certs:/var/opt/magma/certs
    - ${HOME}/.blockcast/snowflake:/etc/snowflake
  labels:
    - "com.centurylinklabs.watchtower.enable=true"
  environment:
  - http_proxy=${HTTP_PROXY:-}
  - https_proxy=${HTTPS_PROXY:-}
  - no_proxy=${NO_PROXY:-localhost,127.0.0.1}

services:
  control_proxy:
    <<: *service
    container_name: control_proxy
    command: /usr/bin/control_proxy

  blockcastd:
    <<: *service
    container_name: blockcastd
    command: /usr/bin/blockcastd -logtostderr=true -v=0
    network_mode: bridge
    environment:
    - http_proxy=${HTTP_PROXY:-}
    - https_proxy=${HTTPS_PROXY:-}
    - no_proxy=${NO_PROXY:-localhost,127.0.0.1}

  beacond:
    <<: *service
    container_name: beacond
    command: /usr/bin/beacond -logtostderr=true -v=0


  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
